### ISSUE TITLE
Entity Relationship Model

### ISSUE THREAD

**Issue by priyamshankar** [Kr-Shanu/DBMS_Learning_Hacktoberfest2022#1]
The explanation of entity relationship model is missing in this repo.

**Comment by Kr-Shanu** [comment]
Try to be specific, maintain everything in a folder, write your name in every file and do mention the source wherever possible with proper formatting. All the best @priyamshankar

**Comment by Kr-Shanu** [comment]
Successfully merged the pull request for this issue.
