### ISSUE TITLE
Chapter 2: ER Model

### ISSUE THREAD

**Issue by Kr-Shanu** [Kr-Shanu/DBMS_Learning_Hacktoberfest2022#6]
Chapter 2 : requires the following topic embedded in a folder containing information on the following topics in readme files.

- [x] 1. ER Model
- [x] 2. Enhanced ER Model
- [x] 3. Minimization of ER Diagram
- [x] 4. ER Model: Generalization, Specialization and Aggregation
- [x] 5. Recursive Relationships
- [x] 6. Impedance Mismatch

**Comment by Kr-Shanu** [comment]
One of the topic is being covered @priyamshankar, great work, hope you with the rest.

**Comment by Rishabhraghwendra18** [comment]
Hi @Kr-Shanu may I work on this issue?

**Comment by Kr-Shanu** [comment]
Please go ahead @Rishabhraghwendra18, do mention which all topics you are gonna cover.

**Comment by Kr-Shanu** [comment]
Thankyou @Rishabhraghwendra18 for contributing
