### ISSUE TITLE
Chapter 3: Relational Model

### ISSUE THREAD

**Issue by Kr-Shanu** [Kr-Shanu/DBMS_Learning_Hacktoberfest2022#7]
Chapter 3: Relational model should be added in a folder containing all the content on the following topics in readme files.

- [x] 1. Relational Model and CODD Rules
- [x] 2. Relational Model
- [x] 3. Keys in Relational Model (Candidate, Super, Primary, Alternate and Foreign)
- [x] 4. Number of possible Superkeys
- [x] 5. Anomalies in Relational Model
- [x] 6. Mapping from ER Model to Relational Model
- [x] 7. Strategies for Schema design
- [x] 8. Schema Integration
- [x] 9. Star Schema in Data Warehouse modeling
- [x] 10. Data Warehouse Modeling | Snowflake Schema
- [x] 11. Dimensional Data Modeling

**Comment by priyamshankar** [comment]
please assign this to me, I want to contribute to it.

**Comment by Kr-Shanu** [comment]
Sure please proceed @priyamshankar

**Comment by Kr-Shanu** [comment]
Good work @priyamshankar, hope to see rest coming from your side.

**Comment by bhanu9546** [comment]
I would like to contribute for Anomalies in Relational Model

**Comment by Kr-Shanu** [comment]
Sure @bhanu9546 proceed with that

**Comment by bhanu9546** [comment]
Please assign Data Warehouse Modeling | Snowflake Schema to me

**Comment by Kr-Shanu** [comment]
sure go ahead @bhanu9546

**Comment by ChitrakshiChhabra** [comment]
I would like to contribute in this unit @Kr-Shanu for the topics 

- [x] Dimensional Data Modeling
- [x] Number of possible Superkeys
- [x] Schema Integration
- [x] Strategies for Schema

please assign me for the same

**Comment by Kr-Shanu** [comment]
go for it @ChitrakshiChhabra

**Comment by Kr-Shanu** [comment]
We are only left with topic number 6 in this module.

**Comment by nileshsrivastava27** [comment]
I would like to contribute in this unit @Kr-Shanu, kindly assign me these topics
-> Mapping from ER Model to Relational Model

**Comment by Kr-Shanu** [comment]
Please proceed with it @nileshsrivastava27
