### ISSUE TITLE
CURD Operations using JAVA

### ISSUE THREAD

**Issue by SurajS27** [Kr-Shanu/DBMS_Learning_Hacktoberfest2022#8]
this file will contain code for CURD Operations using JAVA

**Comment by Kr-Shanu** [comment]
Please provide some description. @SurajS27

**Comment by Kr-Shanu** [comment]
Go on with your code, but try to put it in a new folder and also do some documentation for understanding the code and do mention the issue number in the pull request.

**Comment by SurajS27** [comment]
Abhi thoda busy hai baad maine karde ge code upload

**Comment by Kr-Shanu** [comment]
Sorry but i will have to close this issue, thankyou for your interests
